os:
  - Visual Studio 2015
  
platform: x64
  - x64
  
branches:
  only:
    - master

install:
  - git submodule update --init --recursive
  - set PATH=C:\Program Files\CMake\bin;%PATH%

build:
  verbosity: detailed

configuration:
  - Release
  
environment:
  artifactName: $(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_REPO_COMMIT)-$(CONFIGURATION)
  matrix:
    - env_arch: "x64"
    - env_arch: "x86"
  
before_build:
  - mkdir build
  - cd build
  - if [%env_arch%]==[x64] (
    cmake .. -A x64 )
  - if [%env_arch%]==[x86] (
    cmake .. )
  - mkdir %artifactName%
  
build_script:
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=$(pwd)/%artifactName% ..
  - cmake --build . --config %CONFIGURATION% --target install

artifacts:
  - path: build\%artifactName%
  
